### ISSUE TITLE
"sdkbox.PluginOneSignal.enableInAppAlertNotification(false);" not working

### ISSUE THREAD

**Issue by Jonathan-Hattab** [sdkbox/sdkbox-sample-onesignal#3]
Hi,

I've just integrated OneSignal Push Notifications to my app. It's working great but I need to disable the alerts that are popping up when I'm receiving notifications while I'm in the app.

I used the enableInAppAlertNotification method but it doesn't make any change.

Thanks for helping!

**Comment by yinjimmy** [comment]
can not reproduce your issue. 

https://github.com/sdkbox/sdkbox-sample-cpp317/commit/84c0604d25ab8005a239edc45362c5b0f06c61b5
